[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# lazy static
lazy_static = "1.4.0"
num_enum = "0.6.1"

[features]
DEBUG_TRACE_EXECUTION= []