addSbtPlugin("org.jetbrains" % "sbt-idea-plugin" % "3.15.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.2.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.10.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.20.0")
//addSbtPlugin("com.lihaoyi" % "workbench" % "0.4.1")
